server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: taskflow

  datasource:
    url: jdbc:postgresql://${DB_HOST}:5432/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

  data:
    web:
      pageable:
        serialization-mode: via-dto

  flyway:
    enabled: true